apiVersion: v1
kind: Secret
metadata:
  name: habitspace-dev-secrets
  namespace: habitspace
type: Opaque
data:
  # These are base64 encoded values
  DB_PASSWORD: cG9zdGdyZXM=  # 'postgres' in base64
  JWT_SECRET: eW91ci1qd3Qtc2VjcmV0  # 'your-jwt-secret' in base64
  API_KEY: eW91ci1hcGkta2V5  # 'your-api-key' in base64 