apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: habitspace-dev
  namespace: argocd
spec:
  description: HabitSpace Development Project
  sourceRepos:
    - '*'  
  destinations:
    - namespace: '*'  
      server: '*'   
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

---

# gitops-repo/base/applications/dev.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: habitspace-dev
  namespace: argocd
spec:
  project: habitspace-dev
  sources:
    - repoURL: https://github.com/ZivISM/DevOps-Project.git
      targetRevision: development
      path: app
      helm:
        valueFiles:
          - $values/gitops-repo/environments/development/values.yaml
    - repoURL: https://github.com/ZivISM/DevOps-Project.git
      targetRevision: development
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: habitspace-dev
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true