apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-service
  namespace: habitspace
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.configMap.data.SERVER_PORT | default "5000" }}
      targetPort: {{ .Values.configMap.data.SERVER_PORT | default "5000" }}
      protocol: TCP
      name: http
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
    component: backend 