apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: habitspace
  labels:
    {{- include "habitspace.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.global.environment }}
  API_URL: {{ printf "http://%s-backend:%v" .Release.Name (.Values.backend.service.port) }}
  {{- if .Values.configMap.data }}
  {{- toYaml .Values.configMap.data | nindent 2 }}
  {{- end }} 