apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    {{- include "habitspace.labels" . | nindent 4 }}
  annotations:
    description: "Namespace for HabitSpace application" 
