{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-backend-network-policy
  namespace: habitspace
  labels:
    {{- include "habitspace.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "habitspace.selectorLabels" . | nindent 6 }}
      component: backend
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "habitspace.selectorLabels" . | nindent 14 }}
              component: frontend
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - podSelector:
            matchLabels:
              {{- include "habitspace.selectorLabels" . | nindent 14 }}
              app: postgresql
      ports:
        - protocol: TCP
          port: 5432 
{{- end -}}