{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-backend
  namespace: habitspace
  labels:
    {{- include "habitspace.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "habitspace.selectorLabels" . | nindent 6 }}
      component: backend
      component: frontend
      component: redis
      component: postgres
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end -}} 