{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-backend-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "habitspace.labels" . | nindent 4 }}
spec:
  endpoints:
  - path: /metrics
    port: http
    interval: {{ .Values.monitoring.prometheus.scrapeInterval }}
  selector:
    matchLabels:
      {{- include "habitspace.selectorLabels" . | nindent 6 }}
      component: backend
{{- end }} 