name: Build frontend image
on:
  push:
    branches: [ development ]
    paths:
      - 'app-repo/source/frontend/**'


env:
  DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/habit-tracker-frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push with commit SHA tag
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: app-repo/source/frontend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Update GitOps repository with new image tag
      - name: Update GitOps repository
        env:
          GH_TOKEN: ${{ secrets.GITOPS_PAT }}
        run: |

          # Clone GitOps repo
          git clone https://oauth2:${GH_TOKEN}@github.com/ZivISM/DevOps-Project.git gitops
          cd gitops
          

          yq eval ".frontend.image.tag = \"${GITHUB_SHA}\"" -i "gitops-repo/environments/development/values.yaml"
          
          # Commit and push changes
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update frontend image to ${GITHUB_SHA}"
          git push